apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"